// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  pokeball: string;
  root: string;
  rotate: string;
}
export const cssExports: CssExports;
export default cssExports;
