// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'auto': string;
  'big': string;
  'button': string;
  'green': string;
  'medium': string;
  'small': string;
  'yellow': string;
}
export const cssExports: CssExports;
export default cssExports;
