// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'content': string;
  'homePage': string;
  'parallaxWrapper': string;
  'text': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
