// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  buttonWrapper: string;
  checkboxInput: string;
  checkboxLabel: string;
  checkboxText: string;
  checkboxType: string;
  cloud: string;
  customCheckbox: string;
  dashLabel: string;
  filterContent: string;
  filterMenu: string;
  fromToLabel: string;
  innerRow: string;
  inputNumber: string;
  inputSearch: string;
  root: string;
  show: string;
  text: string;
  toggleButton: string;
  typeItemBlock: string;
}
export const cssExports: CssExports;
export default cssExports;
