// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'active': string;
  'buttonIcon': string;
  'content': string;
  'header': string;
  'logo': string;
  'menu': string;
  'menuButton': string;
  'menuItem': string;
  'menuList': string;
  'show': string;
}
export const cssExports: CssExports;
export default cssExports;
