// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  cardBlock: string;
  cardWrapper: string;
  root: string;
  strongWord: string;
}
export const cssExports: CssExports;
export default cssExports;
