// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  errorText: string;
  errorTextColor: string;
  imageWrapper: string;
  numbers: string;
  root: string;
  teamRocket: string;
}
export const cssExports: CssExports;
export default cssExports;
